#!/bin/bash
# -----------------------------------------------------------------------------
# @brief Hook run after a successful git merge (e.g. from git pull)
# -----------------------------------------------------------------------------

echo "[githook: post-merge] Syncing submodules."
./post-checkout
