#!/bin/bash
# -----------------------------------------------------------------------------
# @brief Prevent accidental push to main or master without PR
# -----------------------------------------------------------------------------

echo "[githook: pre-push] Checking for improper push."

branch=$(git symbolic-ref --short HEAD)

if [[ "$branch" == "main" || "$branch" == "master" ]]; then
    echo "Error: Pushing directly to $branch is disabled. Use a PR instead."
    exit 1
fi
