#include "simulated_transmit_backend.hpp"
#include <fstream>
#include <iomanip>
#include <sstream>
namespace wsprrypi { namespace {std::string esc(const std::string&s){std::string o;for(char c:s){if(c=='"'||c=='\\')o+='\\';o+=c;}return o;}const char* mode_name(TransmissionMode m){switch(m){case TransmissionMode::WSPR:return "WSPR";case TransmissionMode::QRSS:return "QRSS";case TransmissionMode::FSKCW:return "FSKCW";case TransmissionMode::DFCW:return "DFCW";case TransmissionMode::CW:return "CW";case TransmissionMode::TONE:return "TONE";case TransmissionMode::STANDARD_FELD:return "STANDARD_FELD";}return "UNKNOWN";}}
SimulatedTransmitBackend::SimulatedTransmitBackend(IExecutionContext&c,SimulatedBackendConfig x):context_(c),config_(std::move(x)){}
BackendInfo SimulatedTransmitBackend::info()const{return{BackendKind::SIMULATED,"simulated","Hardware-free non-RF execution backend"};}
BackendCapabilities SimulatedTransmitBackend::capabilities()const{BackendCapabilities c;c.output_class=BackendOutputClass::NON_RF_SIMULATION;c.supported_modes=0xffffffffu;c.supports_fade_shape=true;c.supports_precomputed_execution=true;return c;}
void SimulatedTransmitBackend::add(std::string k,long i,std::chrono::nanoseconds n,double h,bool r,std::string d){items_.push_back({std::move(k),i,n.count(),h,r,std::move(d)});}
BackendCompileResult SimulatedTransmitBackend::configure(const ExecutionPlan&p,const BackendExecutionInputs&){items_.clear();json_.clear();stopped_=false;configured_=false;cleanup_armed_=true;cleanup_recorded_=false;plan_id_=p.id;request_id_=p.request_id;plan_mode_=p.mode;add("configure",-1,{},p.reference_frequency_hz,false);if(config_.fail_configure){add("configure_failure",-1,{},0,false,"injected");render();return{false,{},"Injected simulated configure failure."};}if(p.backend!=BackendKind::SIMULATED)return{false,{},"Execution plan is not targeted for simulation."};configured_=true;add("configured",-1,{},p.reference_frequency_hz,false);return{true,{},{}};}
ExecutionResult SimulatedTransmitBackend::execute(const ExecutionPlan&p){if(!configured_||p.id.value!=plan_id_.value)return{false,false,false,"Simulated execution plan is not configured."};add("execution_start",-1,{},p.reference_frequency_hz,false);for(std::size_t i=0;i<p.events.size();++i){auto&e=p.events[i];if(config_.cancel_event==static_cast<long>(i)||stopped_||context_.stopRequested()){add("cancelled",i,e.offset_from_start,0,false,config_.cancel_event==static_cast<long>(i)?"injected":"");render();return{false,true,false,"Simulation cancelled."};}if(config_.fail_event==static_cast<long>(i)){add("execution_failure",i,e.offset_from_start,e.frequency_hz,e.rf_on,"injected");render();return{false,false,true,"Injected simulated execution failure."};}if(!config_.virtual_time&&!context_.waitInterruptibleFor(e.duration)){add("cancelled",i,e.offset_from_start,0,false);render();return{false,true,false,"Simulation cancelled."};}context_.reportExecutionProgress(i);add("event",i,e.offset_from_start,e.frequency_hz,e.rf_on);}add("complete",-1,p.summary.total_duration,0,false);render();return{true,false,false,{}};}
StartupQuiesceResult SimulatedTransmitBackend::quiesceForStartup(){if(config_.fail_startup_quiesce){add("startup_quiesce_failure",-1,{},0,false,"injected");render();return{false,"Injected simulated startup quiesce failure."};}add("startup_quiesce",-1,{},0,false);render();return{true,{}};}void SimulatedTransmitBackend::stop()noexcept{stopped_=true;}
CleanupResult SimulatedTransmitBackend::cleanup()noexcept{const bool fail=cleanup_armed_&&config_.fail_cleanup;if(!cleanup_recorded_){add(fail?"cleanup_failure":"cleanup",-1,{},0,false,fail?"injected":"");cleanup_recorded_=true;}configured_=false;stopped_=false;render();return fail?CleanupResult{false,"Injected simulated cleanup failure."}:CleanupResult{true,{}};}
void SimulatedTransmitBackend::render(){std::ostringstream o;o<<"{\"schema_version\":1,\"backend\":\"simulated\",\"mode\":\""<<mode_name(plan_mode_)<<"\",\"plan_id\":"<<plan_id_.value<<",\"request_id\":"<<request_id_.value<<",\"events\":[";for(size_t i=0;i<items_.size();++i){auto&e=items_[i];if(i)o<<',';o<<"{\"kind\":\""<<esc(e.kind)<<"\",\"event_index\":"<<e.index<<",\"logical_ns\":"<<e.ns<<",\"frequency_hz\":"<<std::setprecision(15)<<e.hz<<",\"rf_on\":"<<(e.rf?"true":"false")<<",\"detail\":\""<<esc(e.detail)<<"\"}";}o<<"]}";json_=o.str();if(!config_.trace_path.empty()){std::ofstream f(config_.trace_path,std::ios::trunc);if(f)f<<json_<<'\n';}}
}
